config/routes.rb
Rails.application.routes.draw do
  	devise_for :user, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
	resources :users do
   		resource :profile do
   			resources :reviews, only: [:new, :create]
		end
	end
	resources :user_steps
	root to: "home#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	#has_many :reviews, dependent: :destroy
	validates :about, presence: true
	validates :user_id, presence: true
	has_one_attached :avatar
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def show
    @user = User.eager_load(:profile).find(params[:user_id])
    @profile = @user.profile
    #@review = Review.new
    #@reviews = Review.where(profile: @profile) 
  end

  def new
    @user = current_user
    @profile = Profile.new
  end

  def edit
    @user = current_user
    @profile = @user.profile
  end

  def create
    @user = current_user
    @profile = @user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to user_profile_path(current_user.id), notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, notice: 'Did not save' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to user_profile_path(current_user.id), notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.fetch(:profile, {}).permit(:about, :avatar)
    end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile, url: user_profile_path(current_user), method: :post) do |f| %>
  
    <div class="field">
      <%= f.label :about %>
      <%= f.text_area :about %>
    </div>

    <div class="field">
      <%= f.file_field :avatar %>
      <% f.label "Profile photo" %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <br>
  <br>
  <br>
  <br>
<h1>Editing Profile</h1>

<%= form_with(model: @profile, url: user_profile_path, method: :patch) do |form| %>
 

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.file_field :avatar %>
    <% form.label "Profile photo" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


</div>

app/views/profiles/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user.first_name%></td>
        <td><%= profile.user.last_name%></td></tr>
        <td><%= link_to 'Show user profile', user_profile_path(current_user, profile) %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/profiles/new.html.erb
<div class="container">
<br>
<br>
<br>
<br>
<br>
<br>

<h1>Hello <%= current_user.first_name %></h1>



<%= form_for(@profile, url: user_profile_path(current_user), method: :post) do |f| %>
  
    <div class="field">
      <%= f.label :about %>
      <%= f.text_area :about %>
    </div>

    <div class="field">
      <%= f.file_field :avatar %>
      <% f.label "Profile photo" %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>®
	
</div>

<%# form_for [:user, @profile] @person do |f| %>
			<%# f.label "Profile photo" %>
			<%# f.file_field :avatar %>
			<%# f.submit 'Upload' %>

app/views/profiles/show.html.erb
<div class="container">



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<% if @profile == current_user.profile  %>
	<strong> Welcome </strong><%= current_user.first_name  %>
<% else  %>
	<strong> This is a profile of </strong><%= @user.first_name  %> <%= @user.last_name  %>
<% end  %>

<p>
  <strong>Street:</strong>
  <%= @user.street %>
</p>

<p>
  <strong>About:</strong>
  <%= @profile.about %>
</p>


	<strong>Profile image</strong>
	<%= image_tag(url_for(@profile.avatar), style: 'width:50px; height:50px;') %>
</p>


<%= link_to 'Edit', edit_user_profile_path(current_user.profile) %>
<%= link_to 'Show other profiles', users_path %>


<div class="container">