config/routes.rb
Rails.application.routes.draw do
  	devise_for :user, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
	resources :users do
   		resource :profile do
   			resources :reviews, only: [:new, :create]
		end
	end
	resources :user_steps
	root to: "home#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_profile
  before_action :set_review, only: :new
  #skip_after_action :verify_policy_scoped, only: :index
  #skip_before_action :authenticate_user!, only: [ :index, :show ]

  def new
    @review = Review.new
    #authorize @review
  end

def create
	#@user = User.find(params[:user_id])
	@profile = Profile.find(params[:profile_id])
	@review = @profile.reviews.build(review_params)
	@review.user_id = current_user.id

	if @review.save
		redirect_to user_profile_path(current_user, @profile)
	else
		redirect_to user_profile_path(current_user, @profile), notice: "Didn't save your review"
	end
end

  private

  def review_params
    params.fetch(:review, {}).permit(:rating, :content)
  end

def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def set_review
   @review = Review.find(params[:id])
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="submit-review">
  <%= form_for([@user, @profile, @review], :url => user_profile_reviews_path(@user, @profile)) do |f| %>
    <label for="review">How was your experience?</label><br>
    <%= f.label :rating %>
    <%= f.select :rating, options_for_select([["Please select one", ""], 5, 4, 3, 2, 1]) %>

    <%= f.text_area :content, placeholder:"Please enter your feedback here" %>
    <%= f.submit "Submit your review", class: "btn btn-default" %> <br><br>
  <% end %>