config/routes.rb
Rails.application.routes.draw do
  	devise_for :user, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "users/registrations" }
	resources :users do
   		resource :profile do
   			resources :reviews, only: [:new, :create]
		end
	end
	resources :user_steps
	root to: "home#index"
end

app/views/layouts/_flash.html.erb
<div class="container">

	<% if flash.any? %>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	<% end %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand pull-left" href="#">
        <img src="<%= image_path('logo_transparent.png') %>" width="147" height="70" class="d-inline-block align-left mr-2">
      </div>
    </div>
    <div class="navbar-collapse collapse">
      
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to 'Home', root_path, method: :get %></li>
          <li><a>About</a></li>
          <li><a>Search</a></li>
          <li><a>Contact</a>

          <% if user_signed_in? %>
            <% if current_user.profile == nil %>
              <li><span class="bg-primary text-white rounded"><%= link_to 'Create profile', new_user_profile_path(current_user.id) %></span></li>
            <% else %>
              <li><span class="bg-primary text-white rounded"><%= link_to 'My profile', user_profile_path(@user) %></span></li>
            <% end %>

          <li><span class="bg-primary text-white rounded"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></span></li>
       
        <% else %>
          <li><div class="log-in-btn"><button class="btn" type="submit"><%= link_to 'Log in', new_user_session_path %></button></div></li>
        <% end %>
        </ul>
      
    </div> <!--/.nav-collapse -->
  </div>

app/views/layouts/_header_address.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <div class="navbar-brand pull-left" href="#">
        <img src="<%= image_path('logo_transparent.png') %>" width="147" height="70" class="d-inline-block align-left mr-2">
      </div>
    </div>
  </div>
</nav>
 

app/views/layouts/_header_rest.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand pull-left" href="#">
        <img src="<%= image_path('logo_transparent.png') %>" width="147" height="70" class="d-inline-block align-left mr-2">
      </div>
    </div>
    <div class="navbar-collapse collapse topnav">
      
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to 'Home', root_path, method: :get %></li>
          <li><a>About</a></li>
          <li><a>Search</a></li>
          <li><a>Contact</a>


      <% if user_signed_in? %>

          <% if current_user.profile == nil %>
            <li><span class="bg-primary text-white rounded"><%= link_to 'Create profile', new_user_profile_path(@user)%></span></li>
          <% else %>
            <li><span class="bg-primary text-white rounded"><%= link_to 'My profile', user_profile_path(current_user) %></span></li>
          <% end %>

        <li><span class="bg-primary text-white rounded"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></span></li>
      <% end %>

        </ul>
      </nav>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neigbornow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :meta %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'autocomplete' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :css %>
   
  </head>
  <body>
    <% if @user.nil? %>
      <%= render 'layouts/header' %>
    <% elsif user_signed_in? && @user.street.nil? %>
      <%= render partial: "layouts/header_address" %>
    <% else %>
      <%= render 'layouts/header_rest' %>
    <% end %>
      <%= render 'layouts/flash' %>
    <div id="main">
    </div>
  </body>
</html>